filebeat.registry.path: /usr/share/data/filebeat/registry

filebeat.config.inputs:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false

logging.files:
  permissions: 0644

#Log Fields:
# a.Date
# a.Time
# a.Level
# a.Env
# a.User
# a.Machine
# a.Node
# a.App
# a.Job
# a.Process
# a.Section
# a.Message    
# a.Err_Numb
# a.Err_Desc
# a.Field 1..10

filebeat.inputs:
# This log is for the mulesoft log
#- type: log
#  processors:
#    - dissect:
#        # INFO  | 2022-02-15 15:59:03,695 | [MuleRuntime].uber.02: [test-elk1].test-elk1Flow.CPU_LITE @42d54b62 | 7d214680-8eaa-11ec-9747-0242b223161a | org.mule.runtime.core.internal.processor.LoggerMessageProcessor | In the main listener
#        # LEVEL | TIME-DATE               | Thread                                                              | Processor/Event                      |Logger Name                                                      | Message
#        tokenizer: "%{a.level} | %{a.date} | [%{a.Process}] | [%{a.mule.procevent}] | %{a.mule.loggername} | %{a.mule.message}"
#        field: "message"
#        target_prefix: ""
#  #INFO  2022-02-15 10:26:35,821 [[MuleRuntime].uber.06: [test-elk1].test-elk1Flow.CPU_LITE @25e12a38] [processor: test-elk1Flow/processors/0; event: a3f09f60-8e7b-11ec-960e-0242b12429d0] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: In the main listener
#  # %-5p %d [%t] [processor: %X{processorPath}; event: %X{correlationId}] %c: %m%n"
#  # %p – the priority level of the logging event.
#  # %d – the default format for the date and time.
#  # %t – the thread name that generated the logging event.
#  # %X – the thread that generated the logging event and the identifier of the message that was processed (correlationId).
#  # %c – the name of the logger that published the logging event.
#  # %m – the application supplied message associated with the logging event.
#  # %n – line separator.
#  enabled: true
#  paths:
#    - /usr/share/filebeat/mule_logs/*.log

  #This log is for the powershell batch framework
- type: filestream
  processors:
    - add_id: ~
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
        match_fields: ["system.process.cgroup.id"]
        match_pids: ["process.pid", "process.parent.pid"]
        match_source: true
        match_source_index: 4
        match_short_id: false
        cleanup_timeout: 60
        labels.dedot: false
    - add_fields:
        target: ""
        fields:
          app.date: ""
          app.time: ""
          app.level: "E"
          app.environment: "DEV"
          app.user: ""
          app.host: ""
          app.node: ""
          app.application: "Oracle"
          app.module: ""
          app.process: ""
          app.section: ""
          #app.message: ""
          app.err_nbr: ""
          app.err_desc: ""
          app.ut: ""
    - copy_fields:
        fields:
            - from: message
              to: app.message
        fail_on_error: false
        ignore_missing: true
  enabled: true
  paths:
    - /usr/share/ora_trc/alert*.log
  include_lines: ['ORA-']

monitoring.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
#output.logstash:
#  hosts: ["logstash:5044"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
